# Generated by Django 6.0.2 on 2026-02-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgertransaction_ledgerentry_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgertransaction'),
        ),
    ]
