# Generated by Django 6.0.2 on 2026-02-08 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrations_oauth_state',
                'indexes': [models.Index(fields=['provider', 'state'], name='integration_provide_209aba_idx'), models.Index(fields=['expires_at'], name='integration_expires_0af107_idx'), models.Index(fields=['used_at'], name='integration_used_at_df5df8_idx')],
            },
        ),
    ]
